<?php

/**
 * @file
 * Contains test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test module.
    case 'help.page.test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description du module test') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function test_theme() {
  return [
    'test' => [
      'render element' => 'children',
    ],
  ];
}
