#!bin/bash
# passage en mode maintenance
#drush sset system.maintenance_mode 1
drush config-set readonlymode.settings enabled 1 -y 
drush cr

#Mise à jour du code
git pull origin master
composer install --no-dev
drush cr

#Mise à jour de la base de données
drush updb
drush cr

#Mise à jour des schemas des types  d'entite
drush entup
drush cr

#export de la config de prod
drush csex prod -y

#import des configs
drush cim -y
drush cr

#Ajout des config de prod au master
git add config/prod
git commit -m 'Ajout des configs de prod'
git push origin master

#sortie de la mode maintenance
#drush sset system.maintenance_mode 0
drush config-set readonlymode.settings enabled 0 -y
drush cr
echo site is online.
