<?php

/**
 * @file
 * Contains consonle_tests.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function consonle_tests_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the consonle_tests module.
    case 'help.page.consonle_tests':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Console testings.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function consonle_tests_theme() {
  return [
    'consonle_tests' => [
      'render element' => 'children',
    ],
  ];
}
